/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { feedbackSubmit } from "../../funcs/feedbackSubmit.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.LogFeedbackRequestBody$inboundSchema,
};

export const tool$feedbackSubmit: ToolDefinition<typeof args> = {
  name: "feedback-submit",
  description: `Log Feedback

Logs new feedback or updates an existing one.

**API Key Types:** API`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await feedbackSubmit(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
