/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { feedbackGetFeedbackById } from "../funcs/feedbackGetFeedbackById.js";
import { feedbackList } from "../funcs/feedbackList.js";
import { feedbackSubmit } from "../funcs/feedbackSubmit.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Feedback extends ClientSDK {
  /**
   * Submit Feedback
   */
  async submit(
    request: operations.SubmitFeedbackRequestBody,
    options?: RequestOptions,
  ): Promise<operations.SubmitFeedbackResponseBody> {
    return unwrapAsync(feedbackSubmit(
      this,
      request,
      options,
    ));
  }

  /**
   * Get All Feedback
   */
  async list(
    request: operations.GetAllFeedbackRequest,
    options?: RequestOptions,
  ): Promise<components.GetAllFeedbackResponse> {
    return unwrapAsync(feedbackList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Feedback by ID
   */
  async getFeedbackById(
    request: operations.GetFeedbackByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetFeedbackByIdResponseBody> {
    return unwrapAsync(feedbackGetFeedbackById(
      this,
      request,
      options,
    ));
  }
}
