/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { queryConversations } from "../funcs/queryConversations.js";
import { queryExportSemanticThreadsQueryResults } from "../funcs/queryExportSemanticThreadsQueryResults.js";
import { queryQueryEvents } from "../funcs/queryQueryEvents.js";
import { queryQueryFeedback } from "../funcs/queryQueryFeedback.js";
import { queryQueryPropertyKeys } from "../funcs/queryQueryPropertyKeys.js";
import { queryQueryPropertyValues } from "../funcs/queryQueryPropertyValues.js";
import { queryQuerySemanticThreads } from "../funcs/queryQuerySemanticThreads.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Query extends ClientSDK {
  /**
   * Query Conversations
   */
  async conversations(
    request: components.QueryConversationsRequestBody,
    options?: RequestOptions,
  ): Promise<components.QueryConversationsResponseBody> {
    return unwrapAsync(queryConversations(
      this,
      request,
      options,
    ));
  }

  /**
   * Query Events
   */
  async queryEvents(
    request: components.QueryEventsRequestBody,
    options?: RequestOptions,
  ): Promise<components.QueryEventsResponseBody> {
    return unwrapAsync(queryQueryEvents(
      this,
      request,
      options,
    ));
  }

  /**
   * Query Feedback
   */
  async queryFeedback(
    request: components.QueryFeedbackRequestBody,
    options?: RequestOptions,
  ): Promise<components.QueryFeedbackResponseBody> {
    return unwrapAsync(queryQueryFeedback(
      this,
      request,
      options,
    ));
  }

  /**
   * Query Semantic Threads
   */
  async querySemanticThreads(
    request: components.QuerySemanticThreadsRequestBody,
    options?: RequestOptions,
  ): Promise<components.QuerySemanticThreadsResponseBody> {
    return unwrapAsync(queryQuerySemanticThreads(
      this,
      request,
      options,
    ));
  }

  /**
   * Export Semantic Threads Query Results
   */
  async exportSemanticThreadsQueryResults(
    request: components.QuerySemanticThreadsRequestBody,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(queryExportSemanticThreadsQueryResults(
      this,
      request,
      options,
    ));
  }

  /**
   * Query Property Keys
   */
  async queryPropertyKeys(
    request?: components.PropertyKeysRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<components.PropertyKeysResponseBody> {
    return unwrapAsync(queryQueryPropertyKeys(
      this,
      request,
      options,
    ));
  }

  /**
   * Query Property Values
   */
  async queryPropertyValues(
    request?: components.PropertyValuesRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<components.PropertyValuesResponseBody> {
    return unwrapAsync(queryQueryPropertyValues(
      this,
      request,
      options,
    ));
  }
}
